# https://circleci.com/docs/2.0/building-docker-images/
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup makefile
          command: make
      - run:
          name: Install requirements
          command: make install
      - run:
          name: Lint code
          command: make lint
